### ISSUE TITLE
Bug fix for processing audio

### ISSUE THREAD

**Issue by tudddorrr** [Epicguru/VoiceChat#2]
In the clientside ProcessAudio function you have a parameter called "samples" but when you write to the player, you write "data" which is the thing the local player sent rather than whatever they received. "Data" should be replaced with "samples" on line 142.

**Comment by Epicguru** [comment]
Hey sekaru,
I'm sorry to reply to this so late, I did not have notifications enabled. I will fix this once I have access to a computer. Thanks!

**Comment by Epicguru** [comment]
Fixed , thanks again.
